name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "MedQuest Step 3"
  comment: "MedQuest HY Step 3"
  url: "https://megamirrorleech.megamirrorleech-7b1.workers.dev/1:/Medquest%20Step%203.7z"
  file_name: "Medquest-Step-3.7z"
  piece_size: 23 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
